Repository codestates-seb/seb39_main_005, pull requests merged in 2022-09, with the labels that each got.

#1 [BE] set: entity initial setting
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/codestates/team5/dailyclub/DailyclubApplication.java
  server/src/main/java/com/codestates/team5/dailyclub/bookmark/controller/BookmarkController.java
  server/src/main/java/com/codestates/team5/dailyclub/bookmark/entity/Bookmark.java
  server/src/main/java/com/codestates/team5/dailyclub/bookmark/repository/BookmarkRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/bookmark/service/BookmarkService.java
  server/src/main/java/com/codestates/team5/dailyclub/common/Auditable.java
  server/src/main/java/com/codestates/team5/dailyclub/location/controller/LocationController.java
  server/src/main/java/com/codestates/team5/dailyclub/location/entity/Location.java
  server/src/main/java/com/codestates/team5/dailyclub/location/repository/LocationRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/location/service/LocationService.java
  server/src/main/java/com/codestates/team5/dailyclub/message/controller/MessageController.java
  server/src/main/java/com/codestates/team5/dailyclub/message/entity/Message.java
  server/src/main/java/com/codestates/team5/dailyclub/message/repository/MessageRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/message/service/MessageService.java
  server/src/main/java/com/codestates/team5/dailyclub/notice/controller/NoticeController.java
  server/src/main/java/com/codestates/team5/dailyclub/notice/entity/Notice.java
  server/src/main/java/com/codestates/team5/dailyclub/notice/repository/NoticeRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/notice/service/NoticeService.java
  server/src/main/java/com/codestates/team5/dailyclub/notification/controller/NotificationController.java
  server/src/main/java/com/codestates/team5/dailyclub/notification/entity/Notification.java
  server/src/main/java/com/codestates/team5/dailyclub/notification/repository/NotificationRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/notification/service/NotificationService.java
  server/src/main/java/com/codestates/team5/dailyclub/program/controller/ProgramController.java
  server/src/main/java/com/codestates/team5/dailyclub/program/entity/Program.java
  server/src/main/java/com/codestates/team5/dailyclub/program/repository/ProgramRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/program/service/ProgramService.java
  server/src/main/java/com/codestates/team5/dailyclub/user/controller/UserController.java
  server/src/main/java/com/codestates/team5/dailyclub/user/entity/ApplyUser.java
  server/src/main/java/com/codestates/team5/dailyclub/user/entity/User.java
  server/src/main/java/com/codestates/team5/dailyclub/user/repository/UserRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/user/service/UserService.java
  server/src/main/resources/application.properties
  server/src/test/java/com/codestates/team5/dailyclub/DailyclubApplicationTests.java
Labels: BE

#9 [Fe] feat: Global styles(styled-reset install), ThemeProvider, BrowserRouter
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/pages/Login.js
  client/src/pages/SignUp.js
  client/src/styles.js
Labels: FE

#16 [FE] feat: Layout.js & page file
  client/src/components/AreaFilter.js
  client/src/components/Layout.js
  client/src/components/MessageModal.js
  client/src/pages/MyPage.js
  client/src/pages/NoticeCreate.js
  client/src/pages/NoticeDetail.js
  client/src/pages/NoticeList.js
  client/src/pages/ProgCreate.js
  client/src/pages/ProgUpdate.js
Labels: FE

#17 [FE]feat: typescript
  client/.prettierrc.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/AreaFilter.tsx
  client/src/components/Layout.js
  client/src/components/Layout.tsx
  client/src/components/MessageModal.tsx
  client/src/hooks/useRef.tsx
  client/src/index.js
  client/src/index.tsx
  client/src/pages/Login.js
  client/src/pages/Login.tsx
  client/src/pages/Main.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/NoticeCreate.tsx
  client/src/pages/NoticeDetail.tsx
  client/src/pages/NoticeList.tsx
  client/src/pages/ProgCreate.tsx
  client/src/pages/ProgUpdate.tsx
  client/src/pages/SignUp.tsx
  client/src/styles.tsx
  client/tsconfig.json
Labels: FE

#18 [BE] set: common and Swagger setting
  server/build.gradle
  server/src/main/java/com/codestates/team5/dailyclub/common/audit/Auditable.java
  server/src/main/java/com/codestates/team5/dailyclub/common/dto/MultiResponseDto.java
  server/src/main/java/com/codestates/team5/dailyclub/common/dto/PageInfo.java
  server/src/main/java/com/codestates/team5/dailyclub/config/SwaggerConfig.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: BE

#19 [FE] feat: AreaFilter
  client/src/components/AreaFilter.tsx
Labels: FE, ui

#20 [FE] feat: Header & Wrapper
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Footer.tsx
  client/src/components/Header.tsx
  client/src/components/Layout.tsx
  client/src/pages/Main.tsx
  client/src/pages/SignUp.tsx
Labels: FE, ui

#25 [FE] feat: Message Modal
  client/src/components/Footer.tsx
  client/src/components/Layout.tsx
  client/src/components/MessageModal.tsx
Labels: FE

#28 [FE] Main page, LevelPercent component, add svg
  client/src/App.tsx
  client/src/components/Header.tsx
  client/src/components/LevelPercent.tsx
  client/src/custom.d.ts
  client/src/images/Bookmark.svg
  client/src/images/DownArrow.svg
  client/src/images/LevelBottom.svg
  client/src/images/LevelMiddle.svg
  client/src/images/LevelTop.svg
  client/src/images/Logo.svg
  client/src/images/Message.svg
  client/src/images/Pen.svg
  client/src/images/QuestionMark.svg
  client/src/images/Search.svg
  client/src/images/img.txt
  client/src/pages/Main.tsx
  client/tsconfig.json
Labels: FE, ui

#30 [BE] docs: Update API Documentation
  server/build.gradle
  server/src/main/java/com/codestates/team5/dailyclub/bookmark/entity/Bookmark.java
  server/src/main/java/com/codestates/team5/dailyclub/message/controller/MessageController.java
  server/src/main/java/com/codestates/team5/dailyclub/message/dto/MessageDto.java
  server/src/main/java/com/codestates/team5/dailyclub/message/entity/Message.java
  server/src/main/java/com/codestates/team5/dailyclub/message/mapper/MessageMapper.java
  server/src/main/java/com/codestates/team5/dailyclub/message/service/MessageService.java
  server/src/main/java/com/codestates/team5/dailyclub/notice/controller/NoticeController.java
  server/src/main/java/com/codestates/team5/dailyclub/notice/dto/NoticeDto.java
  server/src/main/java/com/codestates/team5/dailyclub/notice/entity/Notice.java
  server/src/main/java/com/codestates/team5/dailyclub/notice/mapper/NoticeMapper.java
  server/src/main/java/com/codestates/team5/dailyclub/notice/service/NoticeService.java
  server/src/main/java/com/codestates/team5/dailyclub/program/entity/Program.java
  server/src/main/java/com/codestates/team5/dailyclub/user/controller/UserController.java
  server/src/main/java/com/codestates/team5/dailyclub/user/dto/UserDto.java
  server/src/main/java/com/codestates/team5/dailyclub/user/entity/ApplyUser.java
  server/src/main/java/com/codestates/team5/dailyclub/user/entity/User.java
  server/src/main/java/com/codestates/team5/dailyclub/user/mapper/UserMapper.java
  server/src/main/java/com/codestates/team5/dailyclub/user/repository/UserRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/user/service/UserService.java
  server/src/main/resources/application.yml
Labels: documentation, BE

#31 [BE] docs: document program api
  server/src/main/java/com/codestates/team5/dailyclub/program/controller/ProgramController.java
  server/src/main/java/com/codestates/team5/dailyclub/program/dto/ProgramDto.java
  server/src/main/java/com/codestates/team5/dailyclub/program/dto/SearchFilterDto.java
  server/src/main/java/com/codestates/team5/dailyclub/program/entity/Program.java
  server/src/main/java/com/codestates/team5/dailyclub/program/mapper/ProgramMapper.java
  server/src/main/java/com/codestates/team5/dailyclub/program/service/ProgramService.java
Labels: documentation, BE, PROGRAM

#32 [BE] docs: document bookmark api
  server/src/main/java/com/codestates/team5/dailyclub/bookmark/controller/BookmarkController.java
  server/src/main/java/com/codestates/team5/dailyclub/bookmark/dto/BookmarkDto.java
  server/src/main/java/com/codestates/team5/dailyclub/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/com/codestates/team5/dailyclub/bookmark/service/BookmarkService.java
Labels: documentation, BE, BOOKMARK

#33 [BE] docs: Update Message,Notice,User API Documentation
  server/src/main/java/com/codestates/team5/dailyclub/message/controller/MessageController.java
  server/src/main/java/com/codestates/team5/dailyclub/message/dto/MessageDto.java
  server/src/main/java/com/codestates/team5/dailyclub/message/service/MessageService.java
  server/src/main/java/com/codestates/team5/dailyclub/notice/controller/NoticeController.java
  server/src/main/java/com/codestates/team5/dailyclub/notice/dto/NoticeDto.java
  server/src/main/java/com/codestates/team5/dailyclub/user/controller/UserController.java
  server/src/main/resources/application.yml
Labels: documentation, BE

#37 [FE] feat: SNS Btn, ProgressBar component, AreaFilter 수정
  client/src/components/AreaFilter.tsx
  client/src/components/Footer.tsx
  client/src/components/LevelPercent.tsx
  client/src/components/OAuth/OauthGoogleBtn.tsx
  client/src/components/OAuth/OauthNaverBtn.tsx
  client/src/components/ProgressBar.tsx
  client/src/custom.d.ts
  client/src/images/GoogleBtn.svg
  client/src/images/NaverLogo.png
  client/src/pages/Login.tsx
  client/src/pages/Main.tsx
  client/src/pages/SignUp.tsx
Labels: FE

#40 [FE] fix: Program Create Page CSS
  client/src/pages/ProgCreate.tsx
Labels: FE, ui

#46 [FE] Feat: MyPage Profile MockUp
  client/src/pages/MyPage.tsx
Labels: FE, ui, feat, 중요도 : 상

#47 [FE] MyPage Message Tab
  client/src/components/Tab/MessageTab.tsx
  client/src/pages/MyPage.tsx
Labels: FE, UI, Message

#50 [FE] feat: Bookmark Tab
  client/src/components/BookMarkTab.tsx
  client/src/components/Header.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/ProgCreate.tsx
Labels: FE, UI, feat, 중요도 : 중, MyPage

#52 [FE] feat: focus text input
  client/src/pages/ProgCreate.tsx
Labels: FE, feat, 부가 기능, UX

#53 [FE] NoticeDetail Mock up, MyPage img size 수정
  client/src/App.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/NoticeDetail.tsx
Labels: FE, UI, Notice

#56 [FE] feat: Notice List Page & fix: Page URL
  client/src/App.tsx
  client/src/components/Header.tsx
  client/src/pages/NoticeDetail.tsx
  client/src/pages/NoticeList.tsx
  client/src/pages/ProgCreate.tsx
Labels: FE, UI, feat, Notice, 부가 기능, 중요도 : 중

#60 [BE] feat: create program with program image
  server/src/main/java/com/codestates/team5/dailyclub/common/enumeration/CommonEnum.java
  server/src/main/java/com/codestates/team5/dailyclub/common/enumeration/converter/AbstractEnumAttributeConverter.java
  server/src/main/java/com/codestates/team5/dailyclub/common/mapper/CommonMapper.java
  server/src/main/java/com/codestates/team5/dailyclub/image/dto/ProgramImageDto.java
  server/src/main/java/com/codestates/team5/dailyclub/image/entity/ProgramImage.java
  server/src/main/java/com/codestates/team5/dailyclub/image/mapper/ProgramImageMapper.java
  server/src/main/java/com/codestates/team5/dailyclub/image/repository/ProgramImageRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/image/service/ProgramImageService.java
  server/src/main/java/com/codestates/team5/dailyclub/image/util/ImageUtils.java
  server/src/main/java/com/codestates/team5/dailyclub/location/controller/LocationController.java
  server/src/main/java/com/codestates/team5/dailyclub/location/entity/Location.java
  server/src/main/java/com/codestates/team5/dailyclub/location/repository/LocationRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/location/service/LocationService.java
  server/src/main/java/com/codestates/team5/dailyclub/program/controller/ProgramController.java
  server/src/main/java/com/codestates/team5/dailyclub/program/dto/ProgramDto.java
  server/src/main/java/com/codestates/team5/dailyclub/program/dto/SearchFilterDto.java
  server/src/main/java/com/codestates/team5/dailyclub/program/entity/Program.java
  server/src/main/java/com/codestates/team5/dailyclub/program/mapper/ProgramMapper.java
  server/src/main/java/com/codestates/team5/dailyclub/program/service/ProgramService.java
  server/src/main/java/com/codestates/team5/dailyclub/program/util/LocationConverter.java
  server/src/main/java/com/codestates/team5/dailyclub/program/util/ProgramStatusConverter.java
Labels: BE, feat, Program, 핵심 기능, 중요도 : 상, DB

#70 [BE] chore: add EnumValueConvertUtils.java and SwaggerController.java
  server/src/main/java/com/codestates/team5/dailyclub/common/util/EnumValueConvertUtils.java
  server/src/main/java/com/codestates/team5/dailyclub/swagger/SwaggerController.java
Labels: BE, hotfix

#76 [FE] feat: Image preview
  client/package.json
  client/src/pages/ProgCreate.tsx
  client/tsconfig.json
Labels: FE, feat, 부가 기능, UX, Image

#75 [BE] fix: initialize targetEnumClass in AbstractConverter
  server/src/main/java/com/codestates/team5/dailyclub/common/enumeration/converter/AbstractEnumAttributeConverter.java
Labels: bug, BE, hotfix

#80 [BE] feat: create apply
  server/src/main/java/com/codestates/team5/dailyclub/apply/controller/ApplyController.java
  server/src/main/java/com/codestates/team5/dailyclub/apply/dto/ApplyDto.java
  server/src/main/java/com/codestates/team5/dailyclub/apply/entity/Apply.java
  server/src/main/java/com/codestates/team5/dailyclub/apply/mapper/ApplyMapper.java
  server/src/main/java/com/codestates/team5/dailyclub/apply/repository/ApplyRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/apply/service/ApplyService.java
Labels: BE, feat, 핵심 기능, 중요도 : 상, Apply

#82 [BE] feat: read program
  server/src/main/java/com/codestates/team5/dailyclub/common/mapper/CommonMapper.java
  server/src/main/java/com/codestates/team5/dailyclub/program/controller/ProgramController.java
  server/src/main/java/com/codestates/team5/dailyclub/program/dto/ProgramDto.java
  server/src/main/java/com/codestates/team5/dailyclub/program/entity/Program.java
  server/src/main/java/com/codestates/team5/dailyclub/program/service/ProgramService.java
  server/test.txt
Labels: BE, feat, Program, 핵심 기능, 중요도 : 상, Apply

#84 [FE] feat: prettier, types folder
  client/.prettierrc.json
  client/src/pages/Login.tsx
  client/src/pages/ProgCreate.tsx
  client/src/pages/SignUp.tsx
  client/src/types/notice.tsx
  client/src/types/programs.tsx
  client/src/types/user.tsx
Labels: FE

#85 [BE] feat: read applies by programId and loginUserId
  server/src/main/java/com/codestates/team5/dailyclub/apply/controller/ApplyController.java
  server/src/main/java/com/codestates/team5/dailyclub/apply/dto/ApplyDto.java
  server/src/main/java/com/codestates/team5/dailyclub/apply/mapper/ApplyMapper.java
  server/src/main/java/com/codestates/team5/dailyclub/apply/repository/ApplyRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/apply/service/ApplyService.java
Labels: BE, feat, Program, 핵심 기능, 중요도 : 상, MyPage, Apply

#95 [Fe] fix: after create userflow
  client/.eslintrc.js
  client/src/pages/Login.tsx
  client/src/pages/ProgCreate.tsx
  client/src/types/notice.tsx
  client/src/types/programs.tsx
Labels: FE, 중요도 : 하, UX

#97 [FE] feat: Login - token 받고 저장하는 틀 작업
  client/src/apis/api.ts
  client/src/apis/localStorage.ts
  client/src/pages/Login.tsx
  client/src/pages/SignUp.tsx
  client/src/types/notice.tsx
  client/src/types/programs.tsx
Labels: FE

#101 [BE] chore: arrange several files
  server/src/main/java/com/codestates/team5/dailyclub/DailyclubApplication.java
  server/src/main/java/com/codestates/team5/dailyclub/common/Auditable.java
  server/src/main/java/com/codestates/team5/dailyclub/config/WebConfig.java
  server/src/main/java/com/codestates/team5/dailyclub/location/controller/LocationController.java
  server/src/main/java/com/codestates/team5/dailyclub/location/entity/Location.java
  server/src/main/java/com/codestates/team5/dailyclub/location/repository/LocationRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/location/service/LocationService.java
  server/src/main/java/com/codestates/team5/dailyclub/program/entity/Program.java
  server/src/main/java/com/codestates/team5/dailyclub/program/util/converter/LocationConverter.java
  server/src/main/java/com/codestates/team5/dailyclub/program/util/converter/ProgramStatusConverter.java
  server/src/main/java/com/codestates/team5/dailyclub/user/entity/ApplyUser.java
  server/src/main/resources/application.properties
Labels: BE

#107 [BE] feat: update and delete program with apply and program image
  server/src/main/java/com/codestates/team5/dailyclub/apply/entity/Apply.java
  server/src/main/java/com/codestates/team5/dailyclub/apply/repository/ApplyRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/apply/service/ApplyService.java
  server/src/main/java/com/codestates/team5/dailyclub/image/entity/ProgramImage.java
  server/src/main/java/com/codestates/team5/dailyclub/image/util/ImageUtils.java
  server/src/main/java/com/codestates/team5/dailyclub/program/controller/ProgramController.java
  server/src/main/java/com/codestates/team5/dailyclub/program/dto/ProgramDto.java
  server/src/main/java/com/codestates/team5/dailyclub/program/dto/SearchFilterDto.java
  server/src/main/java/com/codestates/team5/dailyclub/program/entity/Program.java
  server/src/main/java/com/codestates/team5/dailyclub/program/mapper/ProgramMapper.java
  server/src/main/java/com/codestates/team5/dailyclub/program/service/ProgramService.java
  server/src/main/resources/application.yml
Labels: BE, feat, [Program], 핵심 기능, 중요도 : 상

#114 [BE] feat : Authentication processing and authorization processing using jwt
  server/src/main/java/com/codestates/team5/dailyclub/config/SecurityConfig.java
  server/src/main/java/com/codestates/team5/dailyclub/config/WebConfig.java
  server/src/main/java/com/codestates/team5/dailyclub/jwt/AuthDetails.java
  server/src/main/java/com/codestates/team5/dailyclub/jwt/AuthDetailsService.java
  server/src/main/java/com/codestates/team5/dailyclub/jwt/JwtAccessDeniedHandler.java
  server/src/main/java/com/codestates/team5/dailyclub/jwt/TokenProvider.java
  server/src/main/java/com/codestates/team5/dailyclub/jwt/filter/ErrorHandlerFilter.java
  server/src/main/java/com/codestates/team5/dailyclub/jwt/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/team5/dailyclub/jwt/filter/JwtAuthorizationFilter.java
  server/src/main/java/com/codestates/team5/dailyclub/login/JwtAuthorizationFilter.java
  server/src/main/java/com/codestates/team5/dailyclub/refreshToken/RefreshToken.java
  server/src/main/java/com/codestates/team5/dailyclub/refreshToken/RefreshTokenRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/user/repository/UserRepository.java
Labels: BE, 중요도 : 상, Login

#115 [Fe] feat: Read program img & Read apply list
  client/src/components/Loading.tsx
  client/src/custom.d.ts
  client/src/images/BasicImg.jpg
  client/src/images/loading.gif
  client/src/pages/ProgDetail.tsx
  client/src/types/programs.tsx
Labels: FE, feat, [User], [Program], 중요도 : 상, Image, api

#116 [FE] feat: 프로그램 수정 - 이전값세팅, 이미지 분기/ 프로필 기본이미지 / 회원가입 토큰 localStorage 저장
  client/src/App.tsx
  client/src/apis/api.ts
  client/src/components/Header.tsx
  client/src/images/Profile.svg
  client/src/pages/Login.tsx
  client/src/pages/Main.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/ProgUpdate.tsx
Labels: bug, FE, feat, 중요도 : 상, Image

#117 [BE] feat: search programs by Querydsl
  server/build.gradle
  server/src/main/java/com/codestates/team5/dailyclub/common/mapper/CommonMapper.java
  server/src/main/java/com/codestates/team5/dailyclub/config/QuerydslConfig.java
  server/src/main/java/com/codestates/team5/dailyclub/image/util/ImageUtils.java
  server/src/main/java/com/codestates/team5/dailyclub/program/controller/ProgramController.java
  server/src/main/java/com/codestates/team5/dailyclub/program/dto/ProgramDto.java
  server/src/main/java/com/codestates/team5/dailyclub/program/dto/SearchFilterDto.java
  server/src/main/java/com/codestates/team5/dailyclub/program/repository/ProgramRepository.java
  server/src/main/java/com/codestates/team5/dailyclub/program/repository/ProgramRepositoryCustom.java
  server/src/main/java/com/codestates/team5/dailyclub/program/repository/ProgramRepositoryImpl.java
  server/src/main/java/com/codestates/team5/dailyclub/program/service/ProgramService.java
  server/src/main/java/com/codestates/team5/dailyclub/user/mapper/UserMapper.java
  server/src/main/resources/application.yml
Labels: BE, feat, [Program], 핵심 기능, 중요도 : 상

#118 [BE] fix: add mapstruct-lombok binding
  server/build.gradle
Labels: bug, BE

#121 [BE] fix: Security ignoring
  server/src/main/java/com/codestates/team5/dailyclub/config/SecurityConfig.java
Labels: Login

#122 [FE] User고정후 전역상태 isLoggedId, userInfo 저장 / ProgUpdata 파일형식 수정
  client/src/InitProvider.tsx
  client/src/components/Header.tsx
  client/src/pages/Login.tsx
  client/src/pages/Main.tsx
  client/src/pages/ProgUpdate.tsx
  client/src/pages/SignUp.tsx
  client/src/stores/searchSlice.ts
  client/src/stores/store.ts
  client/src/stores/userInfoSlice.ts
Labels: FE, feat, [User], 중요도 : 상, Login, api

#123 [FE]feat: User-info-lookup
  client/src/pages/MyPage.tsx
  client/src/types/user.tsx
Labels: FE, feat, [User], MyPage

#124 [Fe] feat: separate user detail page & pagination
  client/src/pages/Login.tsx
  client/src/pages/ProgCreate.tsx
  client/src/pages/ProgDetail.tsx
  client/src/pages/SignUp.tsx
  client/src/pagination/Pagination.tsx
  client/src/pagination/page.txt
  client/src/types/programs.tsx
Labels: FE, feat, 중요도 : 상, Image, [Apply], api

#127 [FE]feat: User-info-delete
  client/src/pages/MyPage.tsx
  client/src/types/user.tsx
Labels: FE, feat, [User], MyPage

#130 [FE] feat: 프로그램리스트 api수정, Img 처리, Pagenation/ ProgUpdate 수정/ redux-persist/ Logout
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/InitProvider.tsx
  client/src/apis/api.ts
  client/src/components/Header.tsx
  client/src/images/ImgDeleteBtn.svg
  client/src/index.tsx
  client/src/pages/Login.tsx
  client/src/pages/Main.tsx
  client/src/pages/ProgUpdate.tsx
  client/src/pages/SignUp.tsx
  client/src/stores/store.ts
  client/src/stores/userInfoSlice.ts
  client/src/utils/parseJwt.ts
Labels: FE, feat, [User], [Program], 중요도 : 상, Image, api

#132 FE] feat: Modal Api
  client/src/App.tsx
  client/src/components/ApplyModal.tsx
  client/src/components/CancelModal.tsx
  client/src/components/DeleteModal.tsx
  client/src/components/MessageModal.tsx
  client/src/pages/ProgDetail.tsx
Labels: FE, UI, 중요도 : 상, UX, [Apply], api

#133 [BE] feat: handle global error
  server/src/main/java/com/codestates/team5/dailyclub/common/util/EnumValueConvertUtils.java
  server/src/main/java/com/codestates/team5/dailyclub/image/entity/ProgramImage.java
  server/src/main/java/com/codestates/team5/dailyclub/image/util/ImageUtils.java
  server/src/main/java/com/codestates/team5/dailyclub/program/controller/ProgramController.java
  server/src/main/java/com/codestates/team5/dailyclub/program/dto/ProgramDto.java
  server/src/main/java/com/codestates/team5/dailyclub/program/service/ProgramService.java
  server/src/main/java/com/codestates/team5/dailyclub/throwable/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/codestates/team5/dailyclub/throwable/dto/ErrorResponseDto.java
  server/src/main/java/com/codestates/team5/dailyclub/throwable/entity/BusinessLogicException.java
  server/src/main/java/com/codestates/team5/dailyclub/throwable/entity/ExceptionCode.java
  server/src/main/java/com/codestates/team5/dailyclub/validator/annotation/Image.java
  server/src/main/java/com/codestates/team5/dailyclub/validator/annotation/Location.java
  server/src/main/java/com/codestates/team5/dailyclub/validator/annotation/TodayOrAfter.java
  server/src/main/java/com/codestates/team5/dailyclub/validator/validator/ImageValidator.java
  server/src/main/java/com/codestates/team5/dailyclub/validator/validator/LocationValidator.java
  server/src/main/java/com/codestates/team5/dailyclub/validator/validator/TodayOrAfterValidator.java
  server/src/main/resources/application.yml
  server/src/main/resources/errors.properties
Labels: BE, feat, [Program], 핵심 기능, 중요도 : 중

#137 [BE] fix : doFilterInternal, successfulAuthentication, SecurityFilterChain, AuthDetails
  server/src/main/java/com/codestates/team5/dailyclub/config/SecurityConfig.java
  server/src/main/java/com/codestates/team5/dailyclub/jwt/AuthDetails.java
  server/src/main/java/com/codestates/team5/dailyclub/jwt/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/team5/dailyclub/jwt/filter/JwtAuthorizationFilter.java
Labels: BE, Login
